# Generated by Django 5.2.15 on 2026-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_drop_poc_lead_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mega_user',
            field=models.BooleanField(default=False, help_text="Unlocks the AI tools workspace: connect an AI provider and query this user's own POCs. Grantable by admins only.", verbose_name='Mega User'),
        ),
        migrations.AddField(
            model_name='user',
            name='mega_theme_enabled',
            field=models.BooleanField(default=True, help_text='Show the Mega User (red) interface. Ignored for non-Mega Users.'),
        ),
    ]
