# Generated by Django 5.2.15 on 2026-07-29 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('key_hint', models.CharField(blank=True, max_length=20)),
                ('model_id', models.CharField(choices=[('claude-opus-5', 'Claude Opus 5 — most capable'), ('claude-sonnet-5', 'Claude Sonnet 5 — faster, cheaper'), ('claude-haiku-4-5', 'Claude Haiku 4.5 — fastest')], default='claude-opus-5', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
