# Generated by Django 5.2.15 on 2026-06-29 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_template', models.FileField(blank=True, help_text='Default Word template (.docx) for phases without their own.', null=True, upload_to='report_templates/default/', validators=[django.core.validators.FileExtensionValidator(['docx'])])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'report settings',
                'verbose_name_plural': 'report settings',
            },
        ),
    ]
