# Generated by Django 5.2.15 on 2026-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='after_closure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='kind',
            field=models.CharField(choices=[('phase', 'Phase report'), ('custom', 'Custom report'), ('uploaded', 'Uploaded report'), ('final', 'Final report')], max_length=10),
        ),
    ]
